import type { StageAgentAdapter, StageAgentInput, StageAgentResponse } from "../../core/adapters.js"
import type { DocumentationState } from "../../stages/documentation/types.js"
import type { DocumentationArtifact, DocumentationSection, Project } from "../../types/domain.js"

function artifactMode(state: DocumentationState): DocumentationArtifact["mode"] {
  const trackedCount = Object.keys(state.existingDocs).length
  const existingCount = Object.values(state.existingDocs).filter(Boolean).length
  if (existingCount === 0) return "generate"
  if (existingCount === trackedCount) return "update"
  return "mixed"
}

function buildTechnicalSections(project: Project, state: DocumentationState): DocumentationSection[] {
  const mergedStories = state.executionSummaries.flatMap(wave => wave.storiesMerged)
  const waveSummary = state.planSummary.waves.map((wave, index) => {
    return `Wave ${index + 1}: ${wave.goal} (${wave.storyIds.join(", ")}).`
  })
  const sections: DocumentationSection[] = [
    {
      heading: "System Overview",
      content: [
        state.architectureSummary.summary,
        `System shape: ${state.architectureSummary.systemShape}.`,
      ].join(" "),
    },
    {
      heading: "Implementation Waves",
      content: [
        `The implementation plan shipped ${state.planSummary.waveCount} wave(s).`,
        ...waveSummary,
      ].join(" "),
    },
    {
      heading: "Execution Outcome",
      content: [
        `${mergedStories.length} story branches reached a passed state.`,
        state.executionSummaries.some(wave => wave.storiesBlocked.length > 0)
          ? `Blocked stories remain: ${state.executionSummaries.flatMap(wave => wave.storiesBlocked).join(", ")}.`
          : "No blocked stories remain in execution.",
      ].join(" "),
    },
    {
      heading: "Architecture Decisions",
      content: state.architectureSummary.decisions.length > 0
        ? state.architectureSummary.decisions
          .map(decision => `${decision.id}: ${decision.summary}`)
          .join("; ")
        : state.architectureSummary.relevantComponents
          .map(component => `${component.name}: ${component.responsibility}`)
        .join("; "),
    },
  ]

  sections.push({
    heading: "Known Risks",
    content: state.projectReview.findings.length > 0
      ? state.projectReview.findings.map(finding => `${finding.severity} ${finding.category}: ${finding.message}`).join("; ")
      : "No residual project-wide technical risks remain.",
  })

  const updateModeContent = artifactMode(state) === "generate"
    ? "This run generated the technical documentation from project artifacts."
    : `This run updated the technical documentation for ${project.name} using the latest workflow artifacts.`
  sections.push({
    heading: "Update Mode",
    content: updateModeContent,
  })

  return sections
}

function buildFeatureSections(state: DocumentationState): DocumentationSection[] {
  const implementedFeatures = state.prdDigest.criticalAcs.length > 0
    ? state.prdDigest.criticalAcs.map(ac => `${ac.storyId}/${ac.acId}: ${ac.text}`).join("; ")
    : Object.entries(state.prdDigest.acCountByStory)
      .map(([storyId, acCount]) => `${storyId}: ${acCount} acceptance criteria`)
      .join("; ")
  const sections: DocumentationSection[] = [
    {
      heading: "Implemented Features",
      content: implementedFeatures,
    },
    {
      heading: "Supported User Flows",
      content: state.planSummary.waves
        .map((wave, index) => `Wave ${index + 1} delivers ${wave.goal}`)
        .join("; "),
    },
    {
      heading: "Scope Notes",
      content: state.projectReview.overallStatus === "pass_with_risks"
        ? "The shipped scope is complete for the planned stories, with low-risk technical cleanup remaining."
        : "The shipped scope matches the planned stories for this project run.",
    },
  ]

  if (state.revisionCount > 0) {
    sections.push({
      heading: "Limitations",
      content: state.projectReview.findings.length > 0
        ? state.projectReview.findings.map(finding => finding.message).join("; ")
        : "No known scope limitations were raised by project review.",
    })
  }

  return sections
}

function buildReadmeSections(project: Project, state: DocumentationState): DocumentationSection[] {
  return [
    {
      heading: "Overview",
      content: `${project.name} is a simulated delivery project generated by beerengineer_. ${project.description}`,
    },
    {
      heading: "Run",
      content: ["npm install", "npm start", "npm run typecheck"].join("\n"),
    },
    {
      heading: "Docs",
      content: [
        "- docs/technical-doc.md",
        "- docs/features-doc.md",
        "- docs/README.compact.md",
      ].join("\n"),
    },
    {
      heading: "Status",
      content: `Implemented stories: ${Object.keys(state.prdDigest.acCountByStory).join(", ")}. Review status: ${state.projectReview.overallStatus}.`,
    },
  ]
}

function buildArtifact(project: Project, state: DocumentationState): DocumentationArtifact {
  return {
    project: { id: project.id, name: project.name },
    mode: artifactMode(state),
    technicalDoc: {
      title: `${project.name} Technical Documentation`,
      summary: `Technical reference for ${project.name}, generated from architecture, planning, execution, and project review artifacts.`,
      sections: buildTechnicalSections(project, state),
    },
    featuresDoc: {
      title: `${project.name} Features Documentation`,
      summary: `Feature and scope summary for ${project.name}, derived from the PRD and execution results.`,
      sections: buildFeatureSections(state),
    },
    compactReadme: {
      title: project.name,
      summary: `Compact project README for ${project.name}.`,
      sections: buildReadmeSections(project, state),
    },
    knownIssues: state.projectReview.findings.map(finding => `${finding.severity} ${finding.category}: ${finding.message}`),
  }
}

export class FakeDocumentationStageAdapter
  implements StageAgentAdapter<DocumentationState, DocumentationArtifact> {
  constructor(private readonly project: Project) {}

  async step(input: StageAgentInput<DocumentationState>): Promise<StageAgentResponse<DocumentationArtifact>> {
    if (input.kind === "user-message") {
      throw new Error("Documentation stage does not accept user messages")
    }
    if (input.kind === "review-feedback") {
      input.state.lastReviewFeedback = input.reviewFeedback
      input.state.revisionCount++
    }
    return { kind: "artifact", artifact: buildArtifact(this.project, input.state) }
  }
}
